### ISSUE TITLE
Downloads?

### ISSUE THREAD

**Issue by clach04** [Simone3/ReactMediaTracker#10]
Any chance of downloads being available at https://github.com/Simone3/ReactMediaTracker/releases ?

**Comment by Simone3** [comment]
I just posted on the BE repo but I'll just copy the message here for reference: _Hi clach04, sorry for the late response. Unfortunately not, the only way to build and deploy it is manually. This is just a simple personal project that I am not actively supporting, I don't think I can find the time to do anything more at the moment, sorry._
